### ISSUE TITLE
General Request for help...

### ISSUE THREAD

**Issue by jeffmikels** [EPNW/dumble#1]
I'm trying to implement a mumble client library for flutter, and my architecture is way different from yours, but I still think you can help me.

When I get voice data, it plays through the speakers not like a chipmunk exactly, but still twice as fast. I'm trying to figure out if the problem is with how I'm processing the opus packets or with the libopus library itself. Would you have time to look at my code and tell me what I'm doing wrong?

The relevant parts for this are `handleUDPPacket` in `connection.dart` and the message parsing code in `messages.dart`

https://github.com/jeffmikels/mumble_flutter/blob/master/lib/src/

**Comment by EP-u-NW** [comment]
Hm, I think the problem might be on the playback side. If you say that it is exactly twice as fast as it should be I'd guess that the thing you play your sound with is configured for stereo audio, but all mumble packets are mono audio.

Edit: So I assume the problem is in [line 105 here](https://github.com/jeffmikels/audiostream/blob/main/android/src/main/kotlin/org/jeffmikels/audiostream/AudiostreamPlugin.kt), at least with Android. You could try if changing `AudioFormat.CHANNEL_OUT_STEREO` to `AudioFormat.CHANNEL_OUT_MONO` solves the issue.

**Comment by jeffmikels** [comment]
Thanks for your help. I had no idea mumble was sending mono audio.

I changed the line in the plugin as you recommended, and the speed has been improved, but i'm still getting a ton of audio jitter.

Using your dumble library, I get constant static but can hear very muffled words through it.
Using my mumble_flutter library, I get truly quiet silence, but the words are jittery.

I know I must be using the opus decoder improperly, but it also seems like I'm not using your library properly either.


My dumble listener looks like this:

```dart
class JeffsAudioListener with dumble.AudioListener {
  JeffsAudioListener();

  @override
  void onAudioReceived(
    Stream<dumble.AudioFrame> voiceData,
    dumble.AudioCodec codec,
    dumble.User speaker,
    dumble.TalkMode talkMode,
  ) {
    StreamController<List<int>> sc;
    sc = StreamController();
    sc.stream.listen((event) {
      Audiostream.write(event);
      print('audio');
      print(event);
    });

    if (codec == dumble.AudioCodec.opus) {
      var decoder = StreamOpusDecoder.bytes(
        floatOutput: false,
        sampleRate: 48000,
        channels: 1,
      );
      voiceData
          .map<Uint8List>((dumble.AudioFrame frame) => frame.frame)
          .transform(decoder)
          .cast<List<int>>()
          .pipe(Audiostream.consumer)
          .then((_) async {
        await sc.close();
        print('${speaker.name} stopped');
      });
    }
  }
}

```

**Comment by EP-u-NW** [comment]
Can this be closed?
