### ISSUE TITLE
Having problems with whispers... Am I doing this right?

### ISSUE THREAD

**Issue by jeffmikels** [EPNW/dumble#3]
```dart
  AudioFrameSink whisperTo(User user) {
    user.registerAsVoiceTarget(id: 1);
    return client.audio.sendAudio(voiceTarget: 1, codec: AudioCodec.opus);
  }
```

**Comment by EP-u-NW** [comment]
Yes, it should work this way.
Could you elaborate, what kind of problems appear? Are you testing against an other dumble instance or against something other (e.g. the official mumble client)?
What I could think of is that the mumble server processes the `registerAsVoiceTarget` call to late, so when you start sending audio, the voice target is not registered yet... Could you, for debugging, add a delay (let's say of about 5 secs, just to be sure) before makeing the `sendAudio` call?

**Comment by jeffmikels** [comment]
Thanks for your reply.

Your suggestion sounds plausible. I'll test it with a delay.

On another note, what do you think about making commands like `registerAsVoiceTarget` into Futures?

**Comment by jeffmikels** [comment]
I think I fixed it with this commit: 

https://github.com/EPNW/dumble/pull/2/commits/bcf50f6c6c07d6258d155b4779dd8ac6912e5cfa

Here is the relevant fix:
```dart
Proto.VoiceTarget serializeVoiceTarget(VoiceTarget voiceTarget) {
  Proto.VoiceTarget target = new Proto.VoiceTarget()..id = voiceTarget.id;
```

Your code wasn't preserving the voiceTarget.id.
