### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libopus_x64.dll" not found) 

### ISSUE THREAD

**Issue by resilientbd** [EPNW/dumble#4]
I am facing load dynamic library when I try to run the audio example. but connect example working fine. Is there any solution for this?

**Comment by EP-u-NW** [comment]
The audio examples won't run out of the box, you need to provide the opus audio codec in compiled form (in Windows as .dll, Linux as .so). See the [opus_dart](https://github.com/EPNW/opus_dart) project, especially the section `What is lib?`.

**Comment by resilientbd** [comment]
Thank you very much for your reply.  I am closing this issue and trying to configure it with open_opus.  Actually, I was trying to find the full sample implementation of the mumble flutter client like the windows client. But your resource is very helpful for me. thanks
