### ISSUE TITLE
would this be able to be used in a flutter app - how about performance ?

### ISSUE THREAD

**Issue by robertnax** [EPNW/dumble#6]
super interesting project in Dart :D very interested and had the same thought if it was possible to make a simple client with dart to mumble.

1 ) Is there any flutter app that is using it ? is it possible to use with flutter on android ?

2) wondering about the networking, is dart really fast enough to handle voice over UDP networking ?

**Comment by EP-u-NW** [comment]
Yes, we are actually using it on a few internal projects (not only android but also ios and desktop linux) and the performance sofar is good. For decoding and encoding voice data we are using [opus_dart](https://github.com/EPNW/opus_dart), which uses a native c api, so performance should not an issue there.

BTW we also plan to publish the plugin we wrote for recording and playing audio on android and ios, but it won't be ready till end of june. So the only thing missing then to an mumble dart app is a frontend.

**Comment by robertnax** [comment]
Thanks alot that is super interesting will absolutely follow this project had an impression that dart wasnt strong on networking side.

Super cool and will be trying it out in the weekend ! and eager on seeing where this project goes, well done !
