### ISSUE TITLE
do you by any chance have a simple flutter example where Dumble is integrated ?

### ISSUE THREAD

**Issue by robertnax** [EPNW/dumble#7]
Not a top fancy one but have got it up running here on PC ( had to downgrade flutter though due to nullesafety etc ) - but would be so cool if you had like a starter flutter example ?

and btw nice work this really got me deeper into Dart !

**Comment by EP-u-NW** [comment]
Sorry, not at the moment... It is planed to do something like that in the future (this or next month) like mentioned in #6, but we currently don't have the capacity to provide an example...

Keep in mind that dumble is only there for mumble transport, you need something to actually encode and decode voice data (there is [opus_flutter](https://pub.dev/packages/opus_flutter) for that), and you would also need something to do the actuall recording and playback of voice data. The later would need to work on every supported flutter platform. The general scheme of a flutter app for mumble could be:

your app (user interface) -> dumble (transport & mumble logic) -> opus_flutter (encoding & decoding) -> audio plugin (playing & recording raw audio streams)
